version: "3"
services:
  python:
    container_name: "python"
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src:/workspace/src
    env_file:
      - .env
    command: sleep infinity
